### ISSUE TITLE
need list of constants in README

### ISSUE THREAD

**Issue by tbrowder** [JJ/p6-math-constants#1]
it would be good for a browsing user to easily see what constants are defined

**Comment by tbrowder** [comment]
Thanks, JJ!

**Comment by JJ** [comment]
My pleasure. Keep them coming :-)

**Comment by tbrowder** [comment]
Okay, as a user of both SI and English units, it would be helpful to use the power of P6 to allow a choice of units where and if practical.

**Comment by JJ** [comment]
Any suggestion on how to do that? Just use different names?

**Comment by JJ** [comment]
I have tried this
    my constant c is export(:DEFAULT) = 299792458;
    my constant c is export(:IMPERIAL) =186,282;
but it does not work. Ideally, it should use the same symbol. I think I could define `multi` subroutines and use internally different values, but that would make everything slower and more complicated. Any other idea?

**Comment by JJ** [comment]
Maybe define a different module, just like "Math::Constants::Imperial" and import it?

**Comment by tbrowder** [comment]
Sounds like a reasonable approach.
