### ISSUE TITLE
Incorrect values for some constants

### ISSUE THREAD

**Issue by kjpye** [JJ/p6-math-constants#18]
1. The module superfluously defines e and pi, and in the case of pi has an incorrect value!

2. Since 2019-05-20, planck's constant and the electron charge have defined values, different to those in this module. According to Wikipedia, the new values are 6.626_070_15e-34 and 1.602_176_634e-19 respectively.

Since that effectively redefines the meter and the ampere, this may have side-effects for other constants. (The obvious one is Planck's reduced constant.)

**Comment by JJ** [comment]
Good catch. I'll try and fix it.

**Comment by kjpye** [comment]
So I looked at fixing it myself using https://physics.nist.gov/cuu/Constants.

Problems..

Why is Boltzmann's constant in eV where everything else is in SI units?

What is magnetic permittivity? Presumably it's meant to be magnetic permeability (see vacuum permeability -- the value is the same).

A postfix operator eV should be defined similarly to c and g. This might help with the Boltzman's constant problem in user code.

How much backward compatibility needs to be retained? Should those two problems be resolved with some sort of version bump? (Along with removing e and pi.)

There are probably other constants at that web site which could be included. I'm happy to do that.

**Comment by JJ** [comment]
No compatibility at all. Feel free to dig in, and I'm immensely grateful
for it.

**Comment by kjpye** [comment]
Pull request created.

I went a bit overboard, fixing a few other things in the process.

But accidentally left Boltzmann's constant in eV :-(

I took the liberty of increasing the version number to 0.1.0

I may raise another pull request for Boltzmann's constant and other constants from the NIST page.

**Comment by JJ** [comment]
I think I'm gonna give you the commit bit. Thanks!
Feel free to do as much as you need.

**Comment by kjpye** [comment]
Fixed with PR19 and PR20
