### ISSUE TITLE
Math::Constants and Physics::Constants

### ISSUE THREAD

**Issue by librasteve** [JJ/p6-math-constants#22]
Dear JJ, I see that you write this in your excellent module:

[in Math::Constants]
my constant plancks-h                     is export = 6.626_070_015e-34;   # exact

In my world (https://github.com/p6steve/raku-Physics-Measure/blob/master/README.md) I would write:

use Physics::Measure;
my $h ♎️ "6.626196e-34 J/s";
say ~($h * 1e34);       #6.626 J/s 
say $h.WHAT;            #(Power)

I am trying to avoid hard coding the physical constants into Physics::Measure since Math::Constants already does a much better job!

I have in mind conceptually::
0. A new raku module - lets say Physics::Constants, it does...
1. use Math::Constants to get the numbers (and unit definition?)
2. for all-symbols { my constant * is export ♎️ "*.Real *.UnitDefn" }

I attach a suggested an informal object mapping diagram - red is Physic::Measure, green is Math::Constant, purple is my new module suggestion.
<img width="837" alt="Screenshot 2020-05-06 21 00 05" src="https://user-images.githubusercontent.com/40125330/81222704-9db9d480-8fdc-11ea-90db-710e744f1635.png">

Please let me know if this makes any sense and you are open to the idea? If so, I am happy to code this up, test and submit - really as you decide.

kind regards
p6steve

**Comment by JJ** [comment]
It makes a lot of sense, and I'm happy you find this useful. But what do you want me to do? You want to merge the two modules and produce a new one?

**Comment by librasteve** [comment]
Hi JJ. Thanks for your comment and support, I suggest that I build a version one Physics::Constant according to the dependency chart - the optimum design may need a couple of changes to Math::Constant. If so, I will make a pull request on Math::Constant. So the work for you will be to accept the pull request when it arrives (probably 1 or 2 weeks).

**Comment by JJ** [comment]
You can also create an issue about what you need, feel free to do it if you
want. Thanks again!
